[workspace]
members = ["zincio", "examples", "zincio-hyper", "zincio-quinn"]
resolver = "2"

[workspace.dependencies]
zincio = { version = "=0.2.23", default-features = false }
zincio-hyper = "=0.2.23"
zincio-quinn = "=0.2.23"

[patch.crates-io]
zincio = { path = "./zincio" }
zincio-hyper = { path = "./zincio-hyper" }
zincio-quinn = { path = "./zincio-quinn" }
