[package]
name = "zincio-examples"
version = "0.0.0"
edition = "2021"
publish = false

[[bin]]
name = "tcp-echo-server"
path = "src/tcp-echo-server/main.rs"

[[bin]]
name = "http-server"
path = "src/http-server/main.rs"

[dependencies]
bytes = "1.11.1"
http-body-util = "0.1.3"
hyper = { version = "1.8.1", features = ["server", "http1"] }
zincio = { workspace = true }
zincio-hyper = { workspace = true }

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]
